Add prune step
Some other minor improvements, too.

diff --git a/git-cleanup b/git-cleanup
--- a/git-cleanup
+++ b/git-cleanup
@@ -2,28 +2,29 @@
 
 GREP="grep --color=never"
 
-usage()
-{
-    echo "$0: {local|remote} [REMOTE]" >&2
-}
-
+progname=$(basename $0)
 mode=$1
 remote=$2
 
+usage()
+{
+    echo "$progname: {local|remote} [REMOTE]" >&2
+}
+
 if [ -z $mode ]; then
-    echo "$0: no mode specified" >&2
+    echo "$progname: no mode specified" >&2
     usage
     exit 1
 fi
 
 if [ $mode != "remote" ] && [ $mode != "local" ]; then
-    echo "$0: unknown mode: $mode" >&2
+    echo "$progname: unknown mode: $mode" >&2
     usage
     exit 1
 fi
 
 if [ $mode == "remote" ] && [ -z $remote ]; then
-    echo "$0: no remote specified" >&2
+    echo "$progname: no remote specified" >&2
     usage
     exit 1
 fi
@@ -31,18 +32,23 @@ fi
 if [ $mode == "local" ]; then
     branches=$(git branch --merged | $GREP -v master | $GREP -v '*')
     if [ -z $branches ]; then
-        echo "$0: no merged local branches found"
+        echo "$progname: no merged local branches found"
         exit 0
     fi
 
     git branch -d $branches
 elif [ $mode == "remote" ]; then
+    if ! git remote prune $remote; then
+        echo "$progname: git prune failed" >&2
+        exit 1
+    fi
+
     branches=$(git branch -r --merged | $GREP $remote/ | \
                $GREP -v master | sed -e "s/$remote\///g")
     if [ -z $branches ]; then
-        echo "$0: no merged remote branches found"
+        echo "$progname: no merged remote branches found"
         exit 0
     fi
 
-    git push $remote --delete
+    git push $remote --delete $branches
 fi
diff --git a/gitsync b/gitsync
--- a/gitsync
+++ b/gitsync
@@ -1,22 +1,23 @@
 #!/bin/bash
 
-usage()
-{
-    echo "$0 SRC_REMOTE DST_REMOTE [BRANCH]" >&2
-}
-
+progname=$(basename $0)
 src_remote=$1
 dst_remote=$2
 branch=$3
 
+usage()
+{
+    echo "$progname SRC_REMOTE DST_REMOTE [BRANCH]" >&2
+}
+
 if [ -z $src_remote ]; then
-    echo "$0: too few arguments" >&2
+    echo "$progname: too few arguments" >&2
     usage
     exit 1
 fi
 
 if [ -z $dst_remote ]; then
-    echo "$0: too few arguments" >&2
+    echo "$progname: too few arguments" >&2
     usage
     exit 1
 fi
@@ -27,17 +28,17 @@ fi
 
 curr_branch=$(git rev-parse --abbrev-ref HEAD)
 if [ $curr_branch != $branch ]; then
-    echo "$0: branch mismatch:" \
+    echo "$progname: branch mismatch:" \
          "current branch is $curr_branch but asked to sync $branch" >&2
     usage
     exit 1
 fi
 
 if ! git pull $src_remote $branch; then
-    echo "$0: pull failed" >&2
+    echo "$progname: pull failed" >&2
     exit 1
 fi
 if ! git push $dst_remote $branch; then
-    echo "$0: push failed" >&2
+    echo "$progname: push failed" >&2
     exit 1
 fi
